version: "3.8"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aabbccdd
      MYSQL_DATABASE: reservation-system
  app:
    build: .
    ports:
      - "8010:8010"
    environment:
      - DATABASE_URL=host.docker.internal
      - DATABASE_NAME=reservation-system
    depends_on:
      - db
